Fix fail to start, XML parse error
On Ubuntu 20.04 with librsvg 2.48.0 the activity does fail to start and
logs contain;

Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 230, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/lib/python3/dist-packages/sugar3/activity/activityinstance.py", line 59, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/ViewSlides.activity/viewslides.py", line 160, in __init__
    activity.Activity.__init__(self, handle)
  File "/usr/lib/python3/dist-packages/sugar3/activity/activity.py", line 468, in __init__
    self.set_icon_from_file(bundle.get_icon())
gi.repository.GLib.Error: rsvg-error-quark: Failed to load image “/usr/share/sugar/activities/ViewSlides.activity/activity/ViewSlides.svg”: XML parse error: error code=201 (3) in (null):28:45: Namespace prefix sodipodi for ry on path is not defined
 (0)

librsvg 2.47.0 introduced stricter namespaces in the XML parser,
https://gitlab.gnome.org/GNOME/librsvg/-/blob/master/NEWS#L67

so add namespace declarations.

Signed-off-by: Ibiam Chihurumnaya <ibiamchihurumnaya@gmail.com>